export const siteConfig = {
  name: 'PayLow',
  fullName: 'PayLow Staffing',
  tagline:
    'At PayLow, we tailor our hiring process to align skilled talent with your unique business needs for optimal success.',
  url: 'https://paylowstaffing.com',
  signUpUrl: 'https://signup.paylowstaffing.com/sign-up',
  termsUrl: 'https://toc.paylowstaffing.com/',
  privacyUrl: 'https://privacy-policy.paylowstaffing.com/',
  contactFormEmbedUrl: 'https://lc.paylowstaffing.com/widget/form/1bJDrrS4rOrnEZPBoXDJ',
  designer: { name: 'Chaim Teitelbaum', url: 'https://www.chaimteitelbaum.com' },
  contact: {
    address: '3 Collage Rd #104 Monsey NY 10952',
    phone: '1-877-3PAYLOW',
    phoneDigits: '729569',
    phoneTel: '18873729569',
    email: 'Hire@paylowstaffing.com',
  },
  social: {
    facebook: '#',
    twitter: 'https://x.com/Paylowstaffing',
    youtube: 'https://www.youtube.com/@PayLowstaffing',
    linkedin: 'https://www.linkedin.com/company/paylow-staffing/',
    whatsapp: 'https://wa.me/+18773729569',
  },
} as const;

export const navLinks = [
  { label: 'Home', href: '/' },
  { label: 'About Us', href: '/about-us' },
  { label: 'How It Works', href: '/how-it-works' },
  { label: 'FAQ', href: '/faq' },
  { label: 'Industries', href: '/industries' },
  { label: 'Testimonials', href: '/testimonials' },
  { label: 'Pricing', href: '/pricing' },
  { label: 'Contact Us', href: '/contact-us' },
] as const;

export const assets = {
  logoGlow: 'https://paylowstaffing.com/wp-content/uploads/2024/11/New-Logo-50-glow.png',
  logoFull: 'https://paylowstaffing.com/wp-content/uploads/2024/11/New-Logo-140.webp',
  homeHero: 'https://paylowstaffing.com/wp-content/uploads/2024/10/h3-slider-man-1.png',
  homeHeroGroup94: 'https://paylowstaffing.com/wp-content/uploads/2024/10/Group-94.png',
  homeHeroGroup93: 'https://paylowstaffing.com/wp-content/uploads/2024/10/Group-93.png',
  homeHeroGroup95: 'https://paylowstaffing.com/wp-content/uploads/2024/10/Group-95.png',
  aboutHeroBg: 'https://paylowstaffing.com/wp-content/uploads/2024/12/qtq80-7dX1SQ.jpeg',
  industriesHeroBg: 'https://paylowstaffing.com/wp-content/uploads/2024/10/pexels-tima-miroshnichenko-5717231.webp',
  howItWorksHeroBg: 'https://paylowstaffing.com/wp-content/uploads/2024/10/how-it-works-introduction-1-1024x683.webp',
  faqHeroBg: 'https://paylowstaffing.com/wp-content/uploads/2024/10/Home-Page-Ing-4.webp',
  testimonialsHeroBg: 'https://paylowstaffing.com/wp-content/uploads/2024/10/colleagues-working-together-office.webp',
  contactHeroBg: 'https://paylowstaffing.com/wp-content/uploads/2024/10/home-property-img.webp',
  industryRealEstate: 'https://paylowstaffing.com/wp-content/uploads/2024/12/qtq80-WKXfNe.jpeg',
  industryEcommerce: 'https://paylowstaffing.com/wp-content/uploads/2024/12/qtq80-l4ZJw3.jpeg',
  industryHealthcare: 'https://paylowstaffing.com/wp-content/uploads/2024/12/qtq80-zYFIE6.jpeg',
  industryIT: 'https://paylowstaffing.com/wp-content/uploads/2024/10/person-working-html-computer-1.webp',
  iconDiscovery: 'https://paylowstaffing.com/wp-content/uploads/2024/11/img-1.png',
  iconTalent: 'https://paylowstaffing.com/wp-content/uploads/2024/11/talen-icon.png',
  iconEvaluation: 'https://paylowstaffing.com/wp-content/uploads/2024/11/evaluation-icon.png',
  iconInterview: 'https://paylowstaffing.com/wp-content/uploads/2024/11/interview-icon.png',
  iconOnboarding: 'https://paylowstaffing.com/wp-content/uploads/2024/11/onboarding-icon.png',
  iconTraining: 'https://paylowstaffing.com/wp-content/uploads/2024/11/training-icon.png',
  whyImage: 'https://paylowstaffing.com/wp-content/uploads/2024/10/home-page-img-3.jpg',
  iconSkillCentric: 'https://paylowstaffing.com/wp-content/uploads/2024/10/skill-centric-2.png',
  iconGuided: 'https://paylowstaffing.com/wp-content/uploads/2024/10/Guided-solution-2a.png',
  iconEmpower: 'https://paylowstaffing.com/wp-content/uploads/2024/10/employee-empower-3.png',
  iconCost: 'https://paylowstaffing.com/wp-content/uploads/2024/10/Cost-icon.png',
  iconSupport: 'https://paylowstaffing.com/wp-content/uploads/2024/10/icon-3.png',
  iconPositive: 'https://paylowstaffing.com/wp-content/uploads/2024/10/icon-2.png',
  iconFlexible: 'https://paylowstaffing.com/wp-content/uploads/2024/10/icon-5.png',
  iconAdapt: 'https://paylowstaffing.com/wp-content/uploads/2024/10/icon-1.png',
  iconNoLockIn: 'https://paylowstaffing.com/wp-content/uploads/2024/10/icon6.png',
  advantageImage: 'https://paylowstaffing.com/wp-content/uploads/2024/10/Home-Page-Ing-4.webp',
  ctaWomen: 'https://paylowstaffing.com/wp-content/uploads/2024/10/Home-Page-Ing-4.webp',
  rectangleAccent: 'https://paylowstaffing.com/wp-content/uploads/2024/10/Rectangle-1.png',
  about01: 'https://paylowstaffing.com/wp-content/uploads/2024/10/aboyt-image-01.webp',
  about02: 'https://paylowstaffing.com/wp-content/uploads/2024/12/qtq80-7dX1SQ.jpeg',
  aboutRecruiter: 'https://paylowstaffing.com/wp-content/uploads/2024/10/recruiter.webp',
  about03: 'https://paylowstaffing.com/wp-content/uploads/2024/10/about-img03.webp',
  about04: 'https://paylowstaffing.com/wp-content/uploads/2024/10/Rectangle-7.png',
  howIntro: 'https://paylowstaffing.com/wp-content/uploads/2024/10/how-it-works-introduction-1-1024x683.webp',
  howApply1: 'https://paylowstaffing.com/wp-content/uploads/2024/10/how-to-apply-1.webp',
  howApply2: 'https://paylowstaffing.com/wp-content/uploads/2024/10/how-to-apply-2.webp',
  pricing7: 'https://paylowstaffing.com/wp-content/uploads/2024/11/7dd.png',
  pricingImage: 'https://paylowstaffing.com/wp-content/uploads/2024/10/pricing-pt-img.webp',
  industriesHero1: 'https://paylowstaffing.com/wp-content/uploads/2024/10/pexels-tima-miroshnichenko-5439443.webp',
  industriesHero2: 'https://paylowstaffing.com/wp-content/uploads/2024/10/pexels-tima-miroshnichenko-5717231.webp',
  industriesAdvantage: 'https://paylowstaffing.com/wp-content/uploads/2024/10/Home-Page-Img-6.webp',
  tColleagues: 'https://paylowstaffing.com/wp-content/uploads/2024/10/colleagues-working-together-office.webp',
  tProperty: 'https://paylowstaffing.com/wp-content/uploads/2024/10/home-property-img.webp',
  tAbout04: 'https://paylowstaffing.com/wp-content/uploads/2024/10/about-img-04.webp',
  tFinancial: 'https://paylowstaffing.com/wp-content/uploads/2024/11/Financial-Services.webp',
  tHomeImg7: 'https://paylowstaffing.com/wp-content/uploads/2024/10/home-image-007.webp',
  tManSlider: 'https://paylowstaffing.com/wp-content/uploads/2024/10/h3-slider-man-1.png',
} as const;

export const reviews = [
  { quote: "Incredible service and quality! We couldn’t be happier with the experience. From start to finish, everything was professional, timely, and exceeded expectations. Highly recommend for anyone looking for reliable and efficient service!", name: 'Jessica M.', role: 'Designer', image: 'tColleagues' },
  { quote: "Exceeded all expectations! I was blown away by the level of detail and care that went into every aspect of the project. The team was responsive and incredibly talented. Definitely coming back for future projects!", name: 'David L.', role: 'Web Designer', image: 'tFinancial' },
  { quote: "Excellent service! The team worked quickly but didn’t cut corners on quality. Communication was great, and I always felt informed. Great results for an affordable price.", name: 'Sarah', role: 'Architecture', image: 'tProperty' },
  { quote: "Great work with minor delays. The final product was excellent, but there were a couple of delays along the way. However, the team was very transparent and managed everything professionally. Overall, still highly recommended!", name: 'John Doe', role: 'IT Expert', image: 'tManSlider' },
  { quote: "Amazing team and quality output! Fantastic experience working with this team! The work quality was exceptional, and they made everything easy from start to finish. We’re thrilled with the results and will definitely return. The whole process was seamless, and the results were top-notch!", name: 'John P.', role: 'Software Engineer', image: 'tAbout04' },
  { quote: "Hiring them was the best choice. They understood exactly what we wanted and delivered more than expected.", name: 'Emily T', role: 'Trainer', image: 'tHomeImg7' },
] as const;

export const videoReviews = [
  { title: 'Perfect Capture Photography', youtubeId: 'u68BWUl94o8' },
  { title: 'Advanced Property Management', youtubeId: 'rWTjw-Ikjzk' },
  { title: 'Texas Real Realtors', youtubeId: 'ZCkRwvdrLtc' },
] as const;
